### ISSUE TITLE
XCX: Material Drop Ratio prevents getting the most common items

### ISSUE THREAD

**Issue by vsub** [slashiee/cemu_graphic_packs#392] opened 2019-08-01 21:13 UTC
Those that you always get if there is a material drop
It doesn't matter what what preset is set

**Comment by lasyan3** [comment] 2019-11-01 10:31
@vsub Can you be more specific? I don't see any issue with the mod.

**Comment by vsub** [comment] 2019-11-01 17:56
For example you want to farm some of the common drops that you almost always get.

For example you are fighting Suids(Primordia=>Theroids)to farm Fleccy Fur(the most common drop)
If any mode is set in that cheat,it will prevent you from getting that item.

The percentage is set to 100% and even if I disable the code that always gives me 3 equipment,I still don't get that item

4 Suids are visible but there are more behind me,and after I check all of the drops,there is not a single one "Fleccy Fur"

![1](https://user-images.githubusercontent.com/5032540/68044829-080d5780-fcd0-11e9-978f-4ae058160be5.jpg)
![2](https://user-images.githubusercontent.com/5032540/68044828-080d5780-fcd0-11e9-9fc0-6af1e62795d9.jpg)

And if I disable the Drop Ratio cheat,then I will always get more than 1
Also,I don't know if it matters when this code is enabled,but I also have all of my characters equipped with drop rate boosting equipments,making it reach 100%

**Comment by lasyan3** [comment] 2019-11-01 23:14
Ok I see what the problem is: the game only allows a maximum of 5 items to be looted in a treasure (let's say you get 3 equipments, then you'll only get at max 2 materials). Since Suids have a maximum of 6 salvageable materials, with the 100% drop ratio preset the first 5 materials are always selected and there's not place left for the sixth (which is, guess who, Fleecy Fur!).
I tried to add more items on treasures but all I get are crashs. So far the only way I see to bypass that, is to replace the 100% preset with a 90%. That way, materials will be looted most of the time, but not always the same.
Not a perfect solution, but I don't see a better one :-/

**Comment by vsub** [comment] 2019-11-01 23:49
Hmm,yes that seems to be the problem,I can't get more than 5 items from a chest and I was wrong about "any mode don't give you that item"
It's just that at below 100%,the chance to get it is random(maybe the lower the drop ratio I choose,the higher the chance to get lower rarity item)

So it seems that's not a bug so I don't know if I should close the issue

**Comment by lasyan3** [comment] 2019-11-02 13:46
For me it's a bug of the mod, since it claims "100%" but not all materials have a chance to be selected.
I'm thinking of a proper fix (if possible) and let you know.

**Comment by lasyan3** [comment] 2019-11-02 21:31
Ok I managed to make a fix for this issue. Now if there are too much items, the code will randomly chose which to keep.
@vsub, could you get the latest version of the packs and let me know if it's work as expected for you?
Same for your 2 other issues, I have fixed them.

**Comment by vsub** [comment] 2019-11-02 22:26
Ok,I will test the game when I have time,but I have one stupid question
It's been almost 3 months since I played the game and I don't remember much of what codes I enabled to gain 10x tickets per killed specific enemy(I can't find the code in the list)

Maybe you change the names or\and something else.
Is the code "Gain Tickets from DLC and TA" that one that gives me more tickets per killed enemy
Maybe I did something to the code because x100 seems too much like cheating(I don't see 10x)

After I update the cheats database,all of my selected cheats got deselected so I don't remember what I had enabled before

**Comment by lasyan3** [comment] 2019-11-03 07:04
Take a look in the BLADE category of the mods:
[image: image.png]
And to have tickets by killing enemies, the only way is to activate offline
squad missions and kill the enemies asked for.

**Comment by vsub** [comment] 2019-11-03 14:40
I can't see that image and I really can't see anywhere from where I can increase the tickets I get by killing an enemy(not all of them,just one)
I remember I was getting the usual x10 but now I get only 3(for example)

And btw,is there is a way to download the older version of the codes before the latest change.
I clear the game without a single crash but now with the 100% drop rate enabled,it crashes(sometimes even at startup)

For example I go to location 204 and there are more than 10 crocodiles in there.I go in the middle of them,start the battle and kill them all in less than 10 seconds when the code is not enabled but when it is,the game keep crashing during the battle

**Comment by lasyan3** [comment] 2019-11-03 14:55
It's this one:
![image](https://user-images.githubusercontent.com/7955594/68087030-3ca91c80-fe52-11e9-91a7-f3fbc7745582.png)

Also for the crash, I cannot reproduce it. Have you any other loot mod activated?

**Comment by vsub** [comment] 2019-11-03 15:25
Hmm that's strange,I have only 4 and I did check for updates and download them
![2019-11-03_151932](https://user-images.githubusercontent.com/5032540/68087467-1ed9b880-fe4e-11e9-8d1b-f549bcf9ef66.jpg)

**Comment by lasyan3** [comment] 2019-11-03 15:31
Right, I just forgot to upload the mod for the tickets... Should be online by the time you read that.
About the crash, still investigating.

**Comment by vsub** [comment] 2019-11-03 16:01
Ok I see it now(not as many as yours but I have the tickets multiplayer

Sadly,there is no change.
Killing enemy that gives me 3t,it gives me 30
Buying something that cost 22 subtracts 220

Killing the crocodiles even at 70% crashes the game

**Comment by lasyan3** [comment] 2019-11-03 16:15
Is it possible to share your save?

**Comment by vsub** [comment] 2019-11-03 16:26
Here.
[101C4D00.zip](https://github.com/slashiee/cemu_graphic_packs/files/3801774/101C4D00.zip)

**Comment by lasyan3** [comment] 2019-11-03 16:32
Thanks. Just pushed new release of the packs, hopefully fixes the tickets (no longer multiplied when you buy materials with them).

**Comment by vsub** [comment] 2019-11-03 16:48
Now the tickets are subtracted correctly,but what I get is not multiplied when I kill an enemy.

**Comment by lasyan3** [comment] 2019-11-03 16:55
Did you activate the "offline squad tasks" mod? You'll **never** get tickets from enemies unless you target the ones required by the squad task.

**Comment by vsub** [comment] 2019-11-03 17:18
I did enable the code(the part that allows you to select a specific task also don't work)
I keep resting the task from Social until I get No14 which is about killing Dilus(those crocodiles in FN204)

Offline missions and More Reward Tickets(x10)are enabled

![2019-11-03_171544](https://user-images.githubusercontent.com/5032540/68089127-b09cf200-fe5d-11e9-8e32-79f51700a50e.jpg)


![2019-11-03_171807](https://user-images.githubusercontent.com/5032540/68089115-99f69b00-fe5d-11e9-8b97-8e243f239739.jpg)

**Comment by lasyan3** [comment] 2019-11-03 17:34
Ok perfect now I see what's wrong (it was just the display of tickets which was wrong). Just uploaded the patch.
Oh by the way, you can now choose the Squad mission with the presets:
![image](https://user-images.githubusercontent.com/7955594/68089382-8e5ca180-fe68-11e9-856c-27bff5b853f2.png)

**Closed** 2019-11-28 20:32 UTC
Labels: cemuhook
