### ISSUE TITLE
Fatal frame 5  about brightness and black face

### ISSUE THREAD

**Issue by abc1048032158** [slashiee/cemu_graphic_packs#436] opened 2020-05-07 15:43 UTC
In fatal frame 5,i can't adjust the brightness and the character 's face is too dark

**Comment by abc1048032158** [comment] 2020-05-07 15:50
![1JAH{O7_{1A1Q%5LHU_XM(S](https://user-images.githubusercontent.com/64975252/81315917-76b1e000-907a-11ea-85a4-07d65b76e888.png)
![Screenshot_20200507_234829](https://user-images.githubusercontent.com/64975252/81315927-7a456700-907a-11ea-8c71-ce2d56d8c335.jpg)

**Comment by abc1048032158** [comment] 2020-05-07 15:53
![Screenshot_20200507_234829](https://user-images.githubusercontent.com/64975252/81316205-d14b3c00-907a-11ea-847b-d61f58305c85.jpg)

**Comment by abc1048032158** [comment] 2020-05-07 15:55
Can anyone solve this problem?

**Comment by Crementif** [comment] 2020-05-09 13:49
Can you upload your log.txt file to pastebin.com after you've launched the game and give us a link to that? It helps us see the problem.

**Comment by abc1048032158** [comment] 2020-05-09 14:00
> 启动游戏后，您可以将log.txt文件上传到pastebin.com并给我们提供链接吗？它可以帮助我们发现问题。

where is the log。txt

**Comment by abc1048032158** [comment] 2020-05-09 14:04
> 启动游戏后，您可以将log.txt文件上传到pastebin.com并给我们提供链接吗？它可以帮助我们发现问题。

how to upload the log.txt？

**Comment by abc1048032158** [comment] 2020-05-09 14:12
> 启动游戏后，您可以将log.txt文件上传到pastebin.com并给我们提供链接吗？它可以帮助我们发现问题。

**Comment by abc1048032158** [comment] 2020-05-09 14:15
This is my log.txt when i play this game in prologue。It has obvious dark face and dim light, and there is no change in game brightness adjustment

[14:01:03] Outdated graphic pack or unknown version in 'D:/cemu_1.18.2/cemu_1.18.2/graphicPacks/example_pack/example_pack\rules.txt'
[14:01:03] ------- Init Cemu 1.18.2c -------
[14:01:03] Init Wii U memory space (base: 0x2322a4a0000)
[14:01:03] mlc01 path: D:\
[14:01:03] CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
[14:01:03] RAM: 32691MB
[14:01:03] Used CPU extensions: SSSE3, SSE4.1, AVX2, AES-NI
[14:05:53] Loading lens5_cafe.rpx
[14:05:53] Creating OpenGL canvas
[14:05:54] Thread quantum set to 100000
[14:05:54] ------- Loaded title -------
[14:05:54] TitleId: 00050000-1014d200
[14:05:54] TitleVersion: v1
[14:05:54] Update path: <mlc01>\usr\title\0005000E\1014D200\ (not present)
[14:05:54] AOC path:    <mlc01>\usr\title\0005000C\1014D200\ (not present)
[14:05:54] Save path:   <mlc01>\usr\save\00050000\1014D200\user\
[14:05:54] Shader cache file: shaderCache\transferable\000500001014d200.bin
[14:05:54] gameprofile path: gameProfiles\000500001014d200.ini
[14:05:54] RPX hash (updated): c499d0e5
[14:05:54] RPX hash (base): c499d0e5
[14:05:54] Loaded module 'lens5_cafe' with checksum 0x52992dcd
[14:05:54] RPL link time: 94ms
[14:05:54] HLE scan time: 63ms
[14:05:54] ------- Active settings -------
[14:05:54] CPU-Mode: Triple-core recompiler (gameprofile)
[14:05:54] Load shared libraries: true (gameprofile)
[14:05:54] GPUBufferCacheAccuracy: high (gameprofile)
[14:05:54] Use precompiled shaders: auto (gameprofile)
[14:05:54] Full sync at GX2DrawDone: true
[14:05:54] Console region: Europe
[14:05:54] Console language: English
[14:05:54] ------- Init OpenGL graphics backend -------
[14:05:54] GL_VENDOR: NVIDIA Corporation
[14:05:54] GL_RENDERER: GeForce GTX 1070/PCIe/SSE2
[14:05:54] GL_VERSION: 4.6.0 NVIDIA 417.35
[14:05:54] Using precompiled shaders: false
[14:05:54] OpenGL extensions:
[14:05:54] ARB_clip_control: available
[14:05:54] ARB_get_program_binary: available
[14:05:54] ARB_clear_texture: available
[14:05:54] ARB_copy_image: available
[14:05:54] NV_depth_buffer_float: available
[14:05:54] Activate graphic pack: Fatal Frame - Project Zero: Maiden of Black Water/Enhancements/Film Grain [Presets: Default Size,Medium Size,Big Size,Disabled]
[14:05:54] Activate graphic pack: Fatal Frame - Project Zero: Maiden of Black Water/Enhancements/LOD Bias [Presets: Normal (Default),Lowest,Very Low,Low,High,Ultra,Extreme]
[14:05:54] Applying patch group 'JapanZeroV0' (Codecave: 01800000-01800004)
[14:05:54] Activate graphic pack: Fatal Frame - Project Zero: Maiden of Black Water/Graphics/Resolution [Presets: 1280x720 (Default),640x360,960x540,1600x900,1920x1080,2560x1440,3200x1800,3840x2160,5120x2880,7680x4320]
[14:05:54] Applying patch group 'FatalF60fpsJP'
[14:05:54] Activate graphic pack: Fatal Frame - Project Zero: Maiden of Black Water/Mods/60FPS
[14:05:54] ------- Init Audio backend -------
[14:05:54] DirectSound: available
[14:05:54] XAudio 2.8: available
[14:05:54] ------- Run title -------
[14:05:57] Shader cache loaded with 1110 shaders. Commited mem 548MB. Took 3251ms
[14:05:57] Recompiler initialized. CPU extensions: LZCNT MOVBE AVX 
[14:05:57] IOSU_CRYPTO: No otp.bin found. Online mode cannot be used
[14:05:57] IOSU_CRYPTO: No Seeprom.bin found. Online mode cannot be used
[14:06:00] IOSU_ACT: using account default in first slot
[14:06:56] Unable to compile shader 7f24c6c72b86cdbe
[14:06:56] OpenGL: Unsupported texture depth format 0x001a
[14:06:56] OpenGL: Unsupported texture depth format 0x001a

**Comment by abc1048032158** [comment] 2020-05-09 14:25
This log.txt is when i adjust brightness.there is no change in game's brightness

[14:21:47] Outdated graphic pack or unknown version in 'D:/cemu_1.18.2/cemu_1.18.2/graphicPacks/example_pack/example_pack\rules.txt'
[14:21:47] ------- Init Cemu 1.18.2c -------
[14:21:47] Init Wii U memory space (base: 0x29094570000)
[14:21:47] mlc01 path: D:\
[14:21:47] CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
[14:21:47] RAM: 32691MB
[14:21:47] Used CPU extensions: SSSE3, SSE4.1, AVX2, AES-NI
[14:21:49] Loading lens5_cafe.rpx
[14:21:50] Creating OpenGL canvas
[14:21:50] Thread quantum set to 100000
[14:21:50] ------- Loaded title -------
[14:21:50] TitleId: 00050000-1014d200
[14:21:50] TitleVersion: v1
[14:21:50] Update path: <mlc01>\usr\title\0005000E\1014D200\ (not present)
[14:21:50] AOC path:    <mlc01>\usr\title\0005000C\1014D200\ (not present)
[14:21:50] Save path:   <mlc01>\usr\save\00050000\1014D200\user\
[14:21:50] Shader cache file: shaderCache\transferable\000500001014d200.bin
[14:21:50] gameprofile path: gameProfiles\000500001014d200.ini
[14:21:50] RPX hash (updated): c499d0e5
[14:21:50] RPX hash (base): c499d0e5
[14:21:50] Loaded module 'lens5_cafe' with checksum 0x52992dcd
[14:21:50] RPL link time: 94ms
[14:21:50] HLE scan time: 63ms
[14:21:50] ------- Active settings -------
[14:21:50] CPU-Mode: Triple-core recompiler (gameprofile)
[14:21:50] Load shared libraries: true (gameprofile)
[14:21:50] GPUBufferCacheAccuracy: high (gameprofile)
[14:21:50] Use precompiled shaders: auto (gameprofile)
[14:21:50] Full sync at GX2DrawDone: true
[14:21:50] Console region: Europe
[14:21:50] Console language: English
[14:21:50] ------- Init OpenGL graphics backend -------
[14:21:50] GL_VENDOR: NVIDIA Corporation
[14:21:50] GL_RENDERER: GeForce GTX 1070/PCIe/SSE2
[14:21:50] GL_VERSION: 4.6.0 NVIDIA 417.35
[14:21:50] Using precompiled shaders: false
[14:21:50] OpenGL extensions:
[14:21:50] ARB_clip_control: available
[14:21:50] ARB_get_program_binary: available
[14:21:50] ARB_clear_texture: available
[14:21:50] ARB_copy_image: available
[14:21:50] NV_depth_buffer_float: available
[14:21:50] Activate graphic pack: Fatal Frame - Project Zero: Maiden of Black Water/Enhancements/Film Grain [Presets: Default Size,Medium Size,Big Size,Disabled]
[14:21:50] Activate graphic pack: Fatal Frame - Project Zero: Maiden of Black Water/Enhancements/LOD Bias [Presets: Normal (Default),Lowest,Very Low,Low,High,Ultra,Extreme]
[14:21:50] Applying patch group 'JapanZeroV0' (Codecave: 01800000-01800004)
[14:21:50] Activate graphic pack: Fatal Frame - Project Zero: Maiden of Black Water/Graphics/Resolution [Presets: 1280x720 (Default),640x360,960x540,1600x900,1920x1080,2560x1440,3200x1800,3840x2160,5120x2880,7680x4320]
[14:21:50] Applying patch group 'FatalF60fpsJP'
[14:21:50] Activate graphic pack: Fatal Frame - Project Zero: Maiden of Black Water/Mods/60FPS
[14:21:50] ------- Init Audio backend -------
[14:21:50] DirectSound: available
[14:21:50] XAudio 2.8: available
[14:21:50] ------- Run title -------
[14:21:53] Shader cache loaded with 1110 shaders. Commited mem 548MB. Took 2974ms
[14:21:53] Recompiler initialized. CPU extensions: LZCNT MOVBE AVX 
[14:21:53] IOSU_CRYPTO: No otp.bin found. Online mode cannot be used
[14:21:53] IOSU_CRYPTO: No Seeprom.bin found. Online mode cannot be used
[14:21:56] IOSU_ACT: using account default in first slot

**Comment by Crementif** [comment] 2020-05-09 14:27
Your Nvidia graphics card driver is very old, update that first.

**Comment by abc1048032158** [comment] 2020-05-09 14:30
I tried the latest graphics driver before, the result is the same. This is a problem with the simulator

**Comment by abc1048032158** [comment] 2020-05-09 14:32
I am now thinking whether this is a problem with the emulator or a graphics package that can fix the problem

**Comment by Crementif** [comment] 2020-05-09 14:37
It's a problem with the emulator if you disable all the graphic packs and still have the problem.

**Comment by abc1048032158** [comment] 2020-05-09 14:43
this problem is also exist without graphic packs，but i means can have some new graphic pack to fix this problem for this game,because i see other game have some brightness fix graphic pack.

**Comment by abc1048032158** [comment] 2020-05-09 14:45
Can you have some method to write this graphics package?

**Comment by Crementif** [comment] 2020-05-09 15:36
I've added a graphic pack to change the brightness of the game in the mod section. You will need to update your graphic packs to get it. Let me know if this solves your issue.

**Comment by abc1048032158** [comment] 2020-05-09 15:42
thanks，i will try

**Comment by abc1048032158** [comment] 2020-05-09 15:51
i use the brightness mod ，but there is no change in game. adjust the brightness option also have no change

**Comment by abc1048032158** [comment] 2020-05-09 16:04
i think the game lack some light source，and adjust the brightness option is no change may be related to this problem

**Comment by Crementif** [comment] 2020-05-09 16:12
The lighting and brightness look the same as my Wii U. I don't think I can fix your issue.

**Comment by abc1048032158** [comment] 2020-05-09 16:27
![Uploading Screenshot_20200510_002506.jpg…]()

**Comment by abc1048032158** [comment] 2020-05-09 16:33
could you give me your wiiu picture and cemu picture of this game? and did you y
use the new mod to make lightness and brightness as same as wiiu ？

**Comment by horxd33** [comment] 2020-05-09 18:36
game source japanese(chinese patch)
no change
[log.txt](https://github.com/slashiee/cemu_graphic_packs/files/4604270/log.txt)
![darker](https://user-images.githubusercontent.com/65086709/81481901-f4860f00-9265-11ea-85a3-329c10e90fce.png)
![much darker](https://user-images.githubusercontent.com/65086709/81481905-f9e35980-9265-11ea-9e40-0118661e1eab.png)
![brighter](https://user-images.githubusercontent.com/65086709/81481922-0798df00-9266-11ea-8ade-4d78de9fc765.png)
![much brighter](https://user-images.githubusercontent.com/65086709/81481928-0bc4fc80-9266-11ea-92e7-361aa766fb54.png)

**Comment by horxd33** [comment] 2020-05-09 19:22
game source europe(wud)
it works, but the face is still black, and the flashlight has no reflection
Flashlight reflection as in the following video
https://www.youtube.com/watch?v=vaGv8n50nro&t=19s
[log.txt](https://github.com/slashiee/cemu_graphic_packs/files/4604324/log.txt)
![eu normal](https://user-images.githubusercontent.com/65086709/81482674-70368a80-926b-11ea-871c-933baf4f17e2.png)
![eu darker](https://user-images.githubusercontent.com/65086709/81482692-8f351c80-926b-11ea-8665-68ee79fdc6e5.png)
![eu much darker](https://user-images.githubusercontent.com/65086709/81482701-9825ee00-926b-11ea-9e29-7c9be353d5dc.png)
![eu brighter](https://user-images.githubusercontent.com/65086709/81482704-a1af5600-926b-11ea-890b-10ac10e5c1ae.png)
![eu much brighter](https://user-images.githubusercontent.com/65086709/81482707-a7a53700-926b-11ea-99a4-fc1518ea2697.png)

**Comment by Crementif** [comment] 2020-05-09 19:37
Hm, I'll take a look at it again, see if something might be wrong.

**Comment by horxd33** [comment] 2020-05-09 19:52
ok, thanks

**Comment by abc1048032158** [comment] 2020-05-10 23:09
what's new about this issue？

**Comment by Crementif** [comment] 2020-05-11 01:28
Nothing yet, didn't have time today. I'll let you guys know tomorrow whether I can do something.

**Comment by abc1048032158** [comment] 2020-05-11 01:34
ok,you are busy with your first

**Comment by abc1048032158** [comment] 2020-05-11 06:21
this brightness mod can use in usa vision,but the light also not solve this problem, this problem is not only to enhance the entire brightness ,this is the game lack of some light sources, The most obvious is that the brightness in the game Settings is adjusted without any change.

**Comment by abc1048032158** [comment] 2020-05-11 06:56
![Screenshot_20200510_002557](https://user-images.githubusercontent.com/64975252/81532791-98bba300-9397-11ea-80a9-307f71ffe5f8.jpg)
![Screenshot_20200510_002506](https://user-images.githubusercontent.com/64975252/81532808-a1ac7480-9397-11ea-8779-038976d58c53.jpg)

**Comment by abc1048032158** [comment] 2020-05-11 06:57
![Screenshot_20200510_002152](https://user-images.githubusercontent.com/64975252/81532861-bab52580-9397-11ea-9fad-2c1115fc17fd.jpg)
![Uploading Screenshot_20200507_234829.jpg…]()

**Comment by abc1048032158** [comment] 2020-05-11 07:05
fps:60 is cemu ,the another is wiiu

**Comment by abc1048032158** [comment] 2020-05-12 05:24
Do you have time today?

**Comment by abc1048032158** [comment] 2020-05-13 00:06
What 's news？

**Comment by Crementif** [comment] 2020-05-13 02:34
I've updated the graphic packs with the following:
- I've added support for the japanese version to the brightness graphic packs so you should be able to try that.
- Cutscenes seem to be more affected by the missing lighting. The workaround pack that I've also added tries to make the cutscenes more visible. The cutscenes look very ugly when you make it very bright however but I can't fix the issue.

This is a Cemu issue that can't be fixed with graphic packs. I will make an issue on the Cemu bug tracker in 1-2 days with information for the Cemu developers, which means they will be aware of this problem. But it's not a simple fix unfortunately so it might take long for it to get properly fixed.

**Comment by abc1048032158** [comment] 2020-05-13 02:47
I really appreciate your hard work and hope the problem can be solved soon

**Comment by abc1048032158** [comment] 2020-05-13 02:58
I hope that one day if the problem can be solved, I hope you can inform me here as soon as possible

**Comment by abc1048032158** [comment] 2020-05-13 03:03
There's another problem，Walkthrough full game with DLC on Vulkan API, in drop 8 script not work if use 60 fps pack. Dynamic shadows work incorrect, there are other minor graphic bugs. Game crash in drop 10, after box cutscene on any emulator settings. On last boss serios graphics glitches.I hope I can also submit this question by the way

**Comment by horxd33** [comment] 2020-05-13 04:17
when the character switches the angle of view (close to the screen), the color of the character can be normally rendered in about one second, (no black face)
[20200513_jp(chinese)_log.txt](https://github.com/slashiee/cemu_graphic_packs/files/4619764/20200513_jp.chinese._log.txt)
![20200513_jp(chinese)](https://user-images.githubusercontent.com/65086709/81770711-abf37d80-9513-11ea-87c1-f300287e8efa.png)

**Comment by horxd33** [comment] 2020-05-13 04:39
eu version
[20200513_eu_log.txt](https://github.com/slashiee/cemu_graphic_packs/files/4619842/20200513_eu_log.txt)
![20200513_eu_01](https://user-images.githubusercontent.com/65086709/81771833-a186b300-9516-11ea-8220-cc13779ed668.png)
![20200513_eu_02](https://user-images.githubusercontent.com/65086709/81771851-a77c9400-9516-11ea-8392-d67066df3ca2.png)

**Comment by Crementif** [comment] 2020-05-13 12:31
> I hope you can inform me here as soon as possible
I will let you know once there's any status update on the issue.

And thanks for letting me know of some of the bugs, it'll help a lot.

**Comment by abc1048032158** [comment] 2020-05-13 12:37
Thanks again!!I really appreciate your attention to this issue.

**Comment by horxd33** [comment] 2020-05-17 05:58
Thanks for your assistance
[20200517_JPN(Chinese Patch)_log.txt](https://github.com/slashiee/cemu_graphic_packs/files/4639720/20200517_JPN.Chinese.Patch._log.txt)
[20200517_EUR_log.txt](https://github.com/slashiee/cemu_graphic_packs/files/4639723/20200517_EUR_log.txt)
Add video description
https://www.youtube.com/playlist?list=PLQC1eaIsp2nCjCcVmVzFXz3gPdtZK7ZwL

**Comment by abc1048032158** [comment] 2020-05-18 12:49
Have there been further developments?

**Comment by Crementif** [comment] 2020-05-18 19:00
I've unfortunately been a little bit busy over the weekend. I'll try to inform you guys soon.

**Comment by abc1048032158** [comment] 2020-05-21 16:02
ok

**Comment by abc1048032158** [comment] 2020-05-24 08:28
Have there been further developments? @Crementif

**Comment by Crementif** [comment] 2020-05-24 12:28
Sorry for having you guys wait so long. :(

I'll create a proper bug report for the devs today so that they can look into it. I'll be sure to reference the videos @horxd33 has made of the bugs.

**Comment by abc1048032158** [comment] 2020-05-24 12:31
ok ，then the tenth drops’s crash can also submit it together.

**Comment by Crementif** [comment] 2020-05-24 12:48
Yeah, someone in the Cemu discord already mentioned it a lot, but I'll include it regardless.

**Comment by abc1048032158** [comment] 2020-05-24 12:53
Thank you and hope to solve the problem as soon as possible.

**Comment by abc1048032158** [comment] 2020-05-24 13:01
If this problem can be solved one day, I would like to be informed as soon as possible. Thank you very much

**Comment by Crementif** [comment] 2020-05-25 03:28
I've reported the main bugs in Fatal Frame to Cemu's bug tracker, see:
- [The crash that occurs at the 10nth drop](http://bugs.cemu.info/issues/347)
- [The missing lighting effect](http://bugs.cemu.info/issues/348)

I found those to be the main issues with this game, and I think fixing the missing light effect might solve the other graphical problems too. But later on I'll create more issues.

Feel free to watch these reports for any changes. I'll close this issue for now (you can still talk here if you want) since it's not really related to the graphic packs.

**Closed by Crementif** 2020-05-25 03:28 UTC
Labels: cemu issue, workaround

**Comment by abc1048032158** [comment] 2020-05-25 03:33
ok

**Comment by abc1048032158** [comment] 2020-05-25 03:45
issues 197 someone asked the question that the 10th drops would crash. Why hasn't it been fixed for so long?

**Comment by abc1048032158** [comment] 2020-05-25 03:48
issues 303 about face blackness is also the same

**Comment by horxd33** [comment] 2020-05-25 05:14
@Crementif
Thank you for your assistance, and if possible, please help to add the two questions mentioned in the video, thank you 👍👍👍
1.
https://www.youtube.com/watch?v=__R674zgK0I
https://www.youtube.com/watch?v=piwwh-ba7bQ
2.
https://www.youtube.com/watch?v=40jVGghaVME
https://www.youtube.com/watch?v=7P8AI7Y51oM

**Comment by Crementif** [comment] 2020-05-25 11:49
Interesting, didn't know they were already reported. I did try to search for them but I guess I missed them.

> bug 197 someone asked the question that the 10th drops would crash. Why hasn't it been fixed for so long?

Because it's not a good bug report. For a good bug report you need to do multiple things, which this person hasn't done. This are:
- Get multiple people to test the crash and mention it. Otherwise it could be bad game files or a settings problem that is causing the crashing.
- Explain clear steps on how to replicate bugs, the developers otherwise would have to play the game until that point to actually debug it. I've provided a save file for that reason.

Also, they actually fixed some other crashing issue on Nvidia GPUs, and fixed several bugs that the game had with Vulkan. Plus Fatal Frame isn't the only game that required attention from the devs.

> bug 303 about face blackness is also the same

Seems like this bug report also missed clear steps on how to replicate the issue but it did show some good comparisons if you opened the zip file. I might include those in my report.

--- 
> Thank you for your assistance, and if possible, please help to add the two questions mentioned in the video, thank you 👍👍👍

I think all the lighting bugs are related to each other. I could bring up the face as being another graphical issue due to the missing lighting, but I just thought it would be clearer if I didn't mention it. Don't know if the water reflections are related, but I would say they're smaller issues that can be reported later.

**Comment by horxd33** [comment] 2020-05-25 14:25
@Crementif
Okay, I was just thinking, that reproducing the problem through the method of the first video, maybe can make the developer it's easier to spot wrong differences, because it is obvious

**Comment by Crementif** [comment] 2020-05-25 15:34
Spent some hours making a workaround for the crashing that happens at the 10nth drop and added it in 8fc9510! It might make it possible to complete the whole game! Feel free to let me know! I probably won't fix the other issues with similar workarounds though.

**Comment by abc1048032158** [comment] 2020-05-25 15:43
I'll test it right away. Thank you for your contribution

**Comment by abc1048032158** [comment] 2020-05-25 16:17
I have already tested it and the problem should be solved.

**Comment by abc1048032158** [comment] 2020-06-01 23:10
about fatal frame ,there is another issues,at last drop, when fight the final boss On the surface of the black water,When you hold up your camera，You can only see the top left quarter of the screen.

**Comment by abc1048032158** [comment] 2020-06-01 23:12
and about black face,have some news？

**Comment by Crementif** [comment] 2020-06-03 22:26
> about fatal frame ,there is another issues,at last drop, when fight the final boss On the surface of the black water,When you hold up your camera，You can only see the top left quarter of the screen.

Oh, does it mean that the whole game is completable now? That's awesome, I'm glad my 10nth drop crash fix could help as much as it did! About the issue, does it happen without any graphic packs?

> and about black face,have some news？

I think the missing lighting and the "black" face are the same issue. It is not totally black, just very dark because of the missing lighting.

I can't say when the developers are going to fix this. It's unknown how difficult this issue is to fix. They are definitely aware of the missing lighting effect though. But they have a lot of things that they can also fix.

Someone else also made a big bug report which listed all the issues with a lot of helpful information so that'll probably help the developers. See the issue [here](http://bugs.cemu.info/issues/351).

**Comment by abc1048032158** [comment] 2020-06-04 03:37
I haven't tried it yet

**Comment by abc1048032158** [comment] 2020-06-16 07:38
the problem of final drop is due to vulkan,change to opengl can solve problem. the only question is face black at present

**Comment by abc1048032158** [comment] 2020-06-16 07:39
Face blackness has been a real problem for several years, except for face blackness, this game can be solved with the 1.11 version of the simulator

**Comment by abc1048032158** [comment] 2020-06-16 07:41
It seems that this issue has not attracted the attention of the author team. Is there any other way to contact the author

**Comment by Crementif** [comment] 2020-06-16 13:42
Just have patience, please. As I said before, the devs have many issues to fix, each one having their own priority and difficulty. And they are definitely aware.

**Comment by horxd33** [comment] 2020-06-20 20:32
[Unable to compile shader & Unsupported texture depth format record sorting(Bug #347,#348,#351,#366).txt](https://github.com/slashiee/cemu_graphic_packs/files/4808516/Unable.to.compile.shader.Unsupported.texture.depth.format.record.sorting.Bug.347.348.351.366.txt)

**Comment by Crementif** [comment] 2020-06-20 20:44
I've already asked about the unsupported texture depth formats to the Cemu devs and he said that they were unrelated. It is the game just doing the wrong stuff.

Cemu does what the Wii U also does in this situation, which is just to make it black. So it shouldn't affect anything.

**Comment by abc1048032158** [comment] 2020-06-20 23:35
I don't really understand your answer，Are there ways around this?

**Comment by Crementif** [comment] 2020-06-20 23:44
I was answering why the log.txt file has errors.

The game developers of Fatal Frame did bad things with depth texture format which is why Cemu gives an error. But Cemu does what the Wii U also does in this situation, so they should look the same.

I don't know why the "Unable to compile shader" error is there exactly, but it's not important and is not causing any graphical issues.

**Comment by horxd33** [comment] 2020-06-21 13:08
Thanks for your comment

**Comment by abc1048032158** [comment] 2020-07-09 23:51
have some progress or news?

**Comment by Crementif** [comment] 2020-07-12 00:09
I mean, I think you're overestimating how much time emulators require to be developed. Cemu wasn't built in a year, it was made over 5 years. Things take time, and getting Fatal Frame working isn't a super high priority task. So please, have some patience!

And no, there isn't any progress or news. It's one of the many problems. I can only say that Cemu 1.12.0 MIGHT has improvements, but who knows. If there's news, I will tell you, so you don't have to keep asking.

**Comment by abc1048032158** [comment] 2020-08-29 00:53
Did the author give up the game？In cemu 1.21，Running black screen under Vulkan，haven't solved the previous problems, but there are still new problems.

**Comment by Crementif** [comment] 2020-08-29 01:44
Stop complaining, it's getting really annoying. Developers would love it if all games magically started working, but that's simply not gonna happen. Also, Fatal Frame works for me on Vulkan with the latest update. There's no new issues on my end.
![fatal frame on latest Cemu version](https://user-images.githubusercontent.com/26669564/91625608-f73d7900-e9a8-11ea-8b54-e0552443f07c.png)
I will lock this thread if you're only gonna use it for nagging, so don't do that. You *could* also provide good feedback.

**Comment by exoduscl** [comment] 2020-09-10 01:45
Hi guys! first of all thanks @Crementif for your patience lol

Does the game have any game breaking bug that prevents completion? or is it only shadows and small stuff like that?

Thanks again!

**Comment by Crementif** [comment] 2020-09-10 01:53
I think that it's fully completable with some graphical bugs atm, since you have the 10th drop fix workaround. That said, I never played fully through it.

**Comment by abc1048032158** [comment] 2020-09-10 02:02
if author can solve the brightness problem ,the game close to profect.

**Comment by exoduscl** [comment] 2020-09-10 02:04
> I think that it's fully completable with some graphical bugs atm, since you have the 10th drop fix workaround now that fixed the only completion stopping crash (though some people are/were experiencing other more random crashes). That said, I never played fully through it so I wouldn't know.

Cool, I'll try it to see how it goes then, thanks and let's hope that Bayoneta 2 and Fatal Frame get the love they deserve now that BOTW is perfect, cheers!

**Comment by Crementif** [comment] 2020-09-10 08:43
> if author can solve the brightness problem ,the game close to profect.

Well, I can tell you that it has been looked into (I think), but it's just complex problem.

**Comment by Crementif** [comment] 2020-09-18 22:09
The new Cemu 1.21.2 seems to have some fixes that might help some issues in Fatal Frame (see http://cemu.info/changelog/cemu_1_21_2.txt). Now, they state that there's no obvious graphical differences (so black face is likely not fixed), but you guys might be able to find any changes in this version. And I thought I'd let you know when the devs spend time looking into Fatal Frame.

**Comment by Crementif** [comment] 2020-09-18 22:42
> about fatal frame ,there is another issues,at last drop, when fight the final boss On the surface of the black water,When you hold up your camera，You can only see the top left quarter of the screen.

Apparently this is fixed with this version! See ![image](https://cdn.discordapp.com/attachments/286445618271092736/756643443177947146/unknown.png)

**Comment by abc1048032158** [comment] 2020-09-18 23:13
perfect! nice!

**Comment by Crementif** [comment] 2020-10-21 23:04
Well, here's the long awaited graphic pack hack that makes some scenes look better... sorta.

I am busy with a personal project and have *wanted* to publish this a proper version of this hack (one that is compatible with all regions of the game and such) for a long time. Since I keep getting bothered about it and I did promise to publish this hack soon, I've decided to just publish what I've got currently and fix it up later. Once I've got time and am done with that project I'll finish a proper version which will get uploaded as an official graphic pack.

So here's the unfinished download (works with the EU/US digital versions):
[FatalFrame_LightingHack.zip](https://github.com/slashiee/cemu_graphic_packs/files/5419072/FatalFrame_LightingHack.zip)

![fix example](https://media.discordapp.net/attachments/456165538771501056/760967590049873998/unknown.png)

Again, this only really makes the flashlight "work". But let me know if there's anything else that has changed.

**Comment by abc1048032158** [comment] 2020-10-21 23:21
nice job!! I will go back to test it later today. Thank you very much for taking time out of your busy schedule to work on this game

**Comment by abc1048032158** [comment] 2020-10-22 05:03
![Uploading %SYZJUO~_JUUW4M141U%JYA.png…]()

**Comment by abc1048032158** [comment] 2020-10-22 05:05
![Uploading %SYZJUO~_JUUW4M141U%JYA.png…]()

**Comment by abc1048032158** [comment] 2020-10-22 05:06
[![%SYZJUO~_JUUW4M141U%JYA](https://user-images.githubusercontent.com/64975252/96827100-66928f00-1467-11eb-9e81-f4478fcb5659.png)
](url)

**Comment by abc1048032158** [comment] 2020-10-22 05:07
Eu version doesn't look like it's changing

**Comment by horxd33** [comment] 2020-10-22 16:21
Using EUR (101d0300) test, there is no change in the light and shadow of the character's face
![20201022_cemu_1 21 3_EUR(101d0300)_Vulkan_01](https://user-images.githubusercontent.com/65086709/96894803-712c4300-14be-11eb-9497-c8c65237c01e.png)
![20201022_cemu_1 21 3_EUR(101d0300)_Vulkan_02](https://user-images.githubusercontent.com/65086709/96893307-25c56500-14bd-11eb-854e-93d9332a4f44.png)

Using USA (101d0600) and installing DLC test, there is no "black face" on the character's face, but there are some white spots on the eyes
When wearing Samus Aran clothing, the badge shows a penetrating effect
![20201022_cemu_1 21 3_USA(101d0600)_Vulkan_01](https://user-images.githubusercontent.com/65086709/96893442-48577e00-14bd-11eb-8042-31eacea5c524.png)
![20201022_cemu_1 21 3_USA(101d0600)_Vulkan_05](https://user-images.githubusercontent.com/65086709/96893739-9c626280-14bd-11eb-9439-4b7da78beeca.png)
![20201022_cemu_1 21 3_USA(101d0600)_Vulkan_06](https://user-images.githubusercontent.com/65086709/96893764-a2584380-14bd-11eb-927a-0a44a51cb128.png)
![20201022_cemu_1 21 3_USA(101d0600)_Vulkan_07](https://user-images.githubusercontent.com/65086709/96893779-a71cf780-14bd-11eb-9a58-6be986aec489.png)

[20201022_cemu_1.21.3_EUR(101d0300) & USA(101d0600)_Vulkan_Test.zip](https://github.com/slashiee/cemu_graphic_packs/files/5424111/20201022_cemu_1.21.3_EUR.101d0300.USA.101d0600._Vulkan_Test.zip)

**Comment by Crementif** [comment] 2020-10-22 17:36
It's only gonna fix it when you've got the flashlight when it can reflect on your face, presumably.

It's up to Cemu to fix the issues it actually has. This is just a hack.

**Comment by horxd33** [comment] 2020-10-22 18:03
Ok, thank you for your contribution to this graphics package

**Comment by abc1048032158** [comment] 2020-10-22 22:24
How to make japan vision can use this graphic packs?

**Comment by horxd33** [comment] 2020-10-24 16:45
Use USA (101d0600) and install DLC test, only open the "LightingHack" graphics package, the light source on the character is on and off when walking (may not be an environmental brightness problem)
https://www.youtube.com/watch?v=feHRzeNa7eE
https://www.youtube.com/watch?v=C_Wo6yd1Ikg
[20201024_cemu_1.21.4_USA(101d0600)_Vulkan_log.txt](https://github.com/slashiee/cemu_graphic_packs/files/5433283/20201024_cemu_1.21.4_USA.101d0600._Vulkan_log.txt)

**Comment by abc1048032158** [comment] 2020-10-27 13:27
there is a bug in second drops, at the beginning of the game, you can't see the camera d when you go to the end of the mountain

**Comment by abc1048032158** [comment] 2020-10-27 13:37
![Uploading ]{N5%R74LYU9OUA}76L4`0Q.png…]()

**Comment by abc1048032158** [comment] 2020-10-27 13:37
![Uploading ]{N5%R74LYU9OUA}76L4`0Q.png…]()

**Comment by abc1048032158** [comment] 2020-10-27 13:37
![{N5%R74LYU9OUA}76L4`0Q](https://user-images.githubusercontent.com/64975252/97309188-a8269e00-189c-11eb-9e29-266796344d0d.png)

**Comment by abc1048032158** [comment] 2020-10-27 13:39
With your latest graphic packs，you can't see the shining camera in the middle of the lake

**Comment by cckpn1234567** [comment] 2020-11-24 09:27
Hi, brothers how are you doing you can fix the Japanese version?

**Comment by Crementif** [comment] 2020-11-25 01:11
We're working on the big V6 graphic pack update (also for Fatal Frame but it won't fix anything, just restructuring what is there) but since the japanese copy has a lot of interest I'll just share it here as a preview [FatalFrame_LightingHack.zip](https://github.com/slashiee/cemu_graphic_packs/files/5593702/FatalFrame_LightingHack.zip). It's not better, just works with the japanese version.

**Comment by abc1048032158** [comment] 2020-11-25 01:20
there is too many bugs in this graphic pack, I don't think this is the best time to release it.

**Comment by abc1048032158** [comment] 2020-11-25 01:29
I think we should fix all the bugs in this graphics package before we release it

**Comment by cckpn1234567** [comment] 2020-11-25 06:47
Thank you, I hope you will complete the final version as soon as possible, come on

**Comment by cckpn1234567** [comment] 2020-11-25 07:26
@Crementif Thank you ,We hope you will complete the final version as soon as possible

**Comment by abc1048032158** [comment] 2020-12-23 01:57
How much progress has been made?

**Comment by chenfan2833** [comment] 2021-01-30 10:20
我们希望您尽快完成最终版本   谢谢

**Comment by Crementif** [comment] 2021-01-30 10:49
There's no final version. This is the best version of the graphic pack.

**Comment by cckpn1234567** [comment] 2021-01-31 10:37
How long does it take to fix the best version of the bug? Because there are too many bugs in this LightingHack now

**Comment by Kriyaaoi** [comment] 2021-08-19 16:40
> There's no final version. This is the best version of the graphic pack.

Thank you for your graphic package, which gives me hope

**Comment by horxd33** [comment] 2021-09-05 07:19
@Kriyaaoi
cemu 1.25.3c Vulkan seems to have changed
https://www.youtube.com/watch?v=9M6tI5fQSew
https://www.youtube.com/watch?v=j4VbVKm6jBE

**Comment by Kriyaaoi** [comment] 2021-09-06 18:00
> @Kriyaaoi
> cemu 1.25.3c Vulkan seems to have changed
> https://www.youtube.com/watch?v=9M6tI5fQSew
> https://www.youtube.com/watch?v=j4VbVKm6jBE

wowThank you for sharing. Although it flickers, it's very surprising to see the normal light

**Comment by Kriyaaoi** [comment] 2021-09-06 19:10
> > There's no final version. This is the best version of the graphic pack.
> 
> Thank you for your graphic package, which gives me hope. Thank you very much
> 
> Bug feedback (I hope it won't disturb you) after opening the graphics package, some enemies close to the wall and obstacles will stop moving, become transparent and can't shoot / attack
> 
> And Hinasaki Miu eyes have abnormal light，The first is open, the second is closed, and the third is wiiu
>
