### ISSUE TITLE
Fatal Frame/Project Zero V5 uncensor Resolution

### ISSUE THREAD

**Issue by IceLancerSR** [slashiee/cemu_graphic_packs#311] opened 2018-12-28 14:14 UTC
Hey there, i saw couple resolved issues regarding this.
So after couple testing with uncensor mods here are my results
Resolution patch applied 1080p

Vanilla not patched 
[EuropeProjectZeroV0]
moduleMatches = 0xB54DBEB0; Vanilla Patch (doesnt work)

moduleMatches = 0x81551809; Uncensored Patch 4 (uncensor + zelda) -doesnt work
moduleMatches = 0x77589D01; Uncensored Patch 5 (uncensor + original kimono) -works
moduleMatches = 0x2897C68C; Uncensored Patch 6 (uncensor + alt kimono) -works

(Doesnt work) means corruption appears in blocks 
https://i.imgur.com/OtH4Cls.jpg

Cemu 1.15e

**Comment by slashiee** [comment] 2018-12-28 19:51
Are you able to provide the log for the ones that don't work?

**Comment by IceLancerSR** [comment] 2018-12-28 20:13
> 
> 
> Are you able to provide logs for the ones that don't work?

Sure , here is vanila game.Untouched disc files
[vanila.zip](https://github.com/slashiee/cemu_graphic_packs/files/2715608/vanila.zip)
ill add rest

**Comment by IceLancerSR** [comment] 2018-12-28 20:30
Yeah for some reason crc patch didnt apply to vanila at all ?according to log
this is shown when crc is working
pplying patch group EuropeProjectZeroV0 from pack 'Resolution' v3 to module lens5_cafe (checksum 0x2897C68C)
but it doesnt have that for vanila game using 0xB54DBEB0

**Comment by skalfate** [comment] 2019-01-05 19:16
I am assuming the disc version and the eshop version might be different checksums. Should be an easy fix hopefully. I'll get on it.

**Comment by skalfate** [comment] 2019-01-05 19:47
I dont know what to say really.. I don't have a copy of the europe edition. The guy who provided the europe version checksums is on discord, and the patches apply properly for many others and him.

In your case if they were different checksums, we could add them, but in your case they dont apply even though same checksum...

Without having access, all I can say redump the game and see if it applies. I'll also forward the issue to Rajkosto, the guy who created cemuhook. He might have know something about why they dont apply.

**Comment by IceLancerSR** [comment] 2019-01-05 19:51
checksum 0xB54DBEB0 does match my rpx file. i dont know about crc's tho , does that matter?

**Comment by IceLancerSR** [comment] 2019-01-05 19:54
I can join discord and provide u with necessary data if that can help.
Which discord is it ?

**Comment by skalfate** [comment] 2019-01-05 20:03
cemus discord is at  https://discord.gg/5psYsup, in gfx channel.

Although your case is unique, in that its the same checksum but the patch doesnt get applied.

**Comment by IceLancerSR** [comment] 2019-01-05 20:09
Ok, im there, but need 10mins on server to be able to talk. Is there anything i can prepare in order to help?

**Comment by skalfate** [comment] 2019-01-05 22:16
Thanks for being patient. I have work, that's why I am not available. But tomorrow come around discord. And we can try to see whats going on.

**Comment by slashiee** [comment] 2019-01-06 01:35
Try using the latest packs and see if the issue is fixed

**Comment by IceLancerSR** [comment] 2019-01-06 02:34
Addendum , if u dont mind, would it be possible to add 2 missing crc's to hub?
 0x77589D01, 0x2897C68C

 (uncensor + original kimono) and  (uncensor + alt kimono) -works

**Comment by slashiee** [comment] 2019-01-06 03:50
Are they both European?

**Comment by skalfate** [comment] 2019-01-06 08:09
Id assume so. I guess we can consider this issue solved. I'll go ahead and close it. If you have further issues. Reopen it for us to discuss.

**Closed by skalfate** 2019-01-06 08:09 UTC

**Comment by IceLancerSR** [comment] 2019-01-06 10:48
Excellent! Yeah they are both EU.

**Comment by shoni89** [comment] 2021-06-26 18:42
I have the problem as well, uncensored EU version, if I use the Resolution GFX I have little dots everywhere. My
[log.1.txt](https://github.com/ActualMandM/cemu_graphic_packs/files/6720541/log.1.txt) is attached here. Thank you

**Comment by Crementif** [comment] 2021-06-27 15:10
Can you try replacing your resolution pack with this: 
[FatalFrameProjectZero_Resolution.zip](https://github.com/ActualMandM/cemu_graphic_packs/files/6721790/FatalFrameProjectZero_Resolution.zip)

**Comment by shoni89** [comment] 2021-06-27 17:33
> Can you try replacing your resolution pack with this [FatalFrameProjectZero_Resolution.zip](https://github.com/ActualMandM/cemu_graphic_packs/files/6721790/FatalFrameProjectZero_Resolution.zip) and see if that fixes it

Sadly no luck, still full of dots... If you need any more info from me let me know, it's probably another case of mismatched crc or something.
