### ISSUE TITLE
[XCX] 60fps don't work anymore with Cemu 1.14.0

### ISSUE THREAD

**Issue by Narihari** [slashiee/cemu_graphic_packs#235] opened 2018-10-31 13:16 UTC
With the new version of Cemu (1.14.0c) it's now impossible to play with the 60fps graphic pack, the game freeze and stay blocked in the "Connection to network" popup when starting the game.
![image](https://user-images.githubusercontent.com/33153067/47790406-5d0e3a80-dd17-11e8-88ad-bf7adb26a4d6.png)

![image](https://user-images.githubusercontent.com/33153067/47790456-816a1700-dd17-11e8-8f9a-b2c242f70ad9.png)

When disabling the 60fps pack it's working perfectly.

**Comment by getdls** [comment] 2018-10-31 19:44
I can't reproduce the issue.. so the only advice I can give you is the same platitudes as every other guide.
Clean install, prebuild cache then only activate 60fps pack.  

![untitled](https://user-images.githubusercontent.com/25286924/47813948-b9d81800-dd4c-11e8-80a3-152e9a36c90f.jpg)

**Comment by Narihari** [comment] 2018-10-31 19:59
> I can't reproduce the issue.. so the only advice I can give you is the same platitudes as every other guide.
> Clean install, prebuild cache then only activate 60fps pack.

Well... same problem
![image](https://user-images.githubusercontent.com/33153067/47815180-e0e41900-dd4f-11e8-8842-02dbf847cdad.png)

**Comment by getdls** [comment] 2018-10-31 20:43
Can you attach a short log zip when it hangs? That'll help us narrow it down.

**Comment by Narihari** [comment] 2018-10-31 21:13
I don't really know if I have to do this like that, but here's my log.zip when starting the game.
[log.zip](https://github.com/slashiee/cemu_graphic_packs/files/2536421/log.zip)

**Comment by Narihari** [comment] 2018-10-31 21:44
Same issue. :c 
[log.zip](https://github.com/slashiee/cemu_graphic_packs/files/2536493/log.zip)

**Comment by getdls** [comment] 2018-10-31 22:19
Sorry, I have no clue what it could be then,  French runs just as well as Japanese for me. 
Your log is fine, drivers, cpu and settings are up to date, there are no errors.

I'll leave this open, maybe some one else runs into similar issues. 
But other than future cemu/cemuhook/gpu driver updates magically solving it we're out of luck. 

![french](https://user-images.githubusercontent.com/25286924/47822107-3fff5900-dd63-11e8-814a-a7b84f842093.jpg)

**Comment by Narihari** [comment] 2018-11-01 08:32
Playing on 1.11.4b let me have 60fps, so i'm gonna wait until a patch come to fix it.

**Comment by Narihari** [comment] 2018-11-03 18:15
Update : i have some textures glitches too.
![image](https://user-images.githubusercontent.com/33153067/47955723-62c88200-df9c-11e8-8de3-566d2a33425b.png)

**Comment by getdls** [comment] 2018-11-05 17:36
I think I know whats happening. There are two checksums for the EUR release
Your -> 0x218F6E07 the one I'm testing -> 0xF882D5CF. 

They probably differ enough for the patch to fail.
I'll look into it after we have sorted the general pack issues first.

**Comment by Narihari** [comment] 2018-11-05 20:50
> _edit_ but why would it work for 1.11.4b then?

I don't know, maybe they changed that on the next version ?

**Comment by zenzetta** [comment] 2018-12-19 22:39
> In my version of the game(US v48) the mod doesn't even seem to start. I'm using Cemu version 1.15.0e. I am able to run the game, but the mod doesn't seem to be on. I have checked multiple times if the mod is on and it is, it just doesn't make my game run at 60fps and the game stays at 30. My setup is more than powerfull enough to push out more frames, since my gpu usage isn't even over 40% usage without the boost clock on and a 4K texture mod and my cpu isn't over 30% usage.
> ![capture](https://user-images.githubusercontent.com/25839757/49991628-020c6c00-ff82-11e8-9cbc-ad1d1757efbd.PNG)

I have the same issue, I just want 60fps. I'm tempted to downgrade my install now.

**Comment by LucentLagombi** [comment] 2018-12-30 22:50
> > In my version of the game(US v48) the mod doesn't even seem to start. I'm using Cemu version 1.15.0e. I am able to run the game, but the mod doesn't seem to be on. I have checked multiple times if the mod is on and it is, it just doesn't make my game run at 60fps and the game stays at 30. My setup is more than powerfull enough to push out more frames, since my gpu usage isn't even over 40% usage without the boost clock on and a 4K texture mod and my cpu isn't over 30% usage.
> > ![capture](https://user-images.githubusercontent.com/25839757/49991628-020c6c00-ff82-11e8-9cbc-ad1d1757efbd.PNG)
> 
> I have the same issue, I just want 60fps. I'm tempted to downgrade my install now.

I have the same issue. It seems like none of the graphics packs or mods I have installed are doing anything.

**Comment by loustak** [comment] 2019-03-11 19:45
Got the same problem with cemu 1.15.3b and cemuhook 0.5.7.0 except that enabling the uncategorized old  60fps graphic pack works but not the one listed under the Xenoblade group. Really strange.

**Comment by yamanobe96** [comment] 2019-03-11 23:52
This issue is resolved in 1.15.2
I'm happy with this version so I'm not up

**Comment by Crementif** [comment] 2019-04-04 09:34
Closing this issue since it seems like it's resolved.

**Closed by Crementif** 2019-04-04 09:34 UTC
Labels: cemuhook
