### ISSUE TITLE
Breath of the Wild - Map Flashing when FPS++ is enabled

### ISSUE THREAD

**Issue by Quixoticed** [slashiee/cemu_graphic_packs#151] opened 2017-12-21 08:49 UTC
Not sure if this is just me. 
Constant flashing (think of seizure inducing flashing) in the map (better explained in the center of the picture, the lens flare effect around the pointer), as if it's being opened again and again. ~Only occurs when the 30fps lock pack is applied~ (Proven false after retesting). Fenceskip is on and FPS++ is enabled.
![untitled](https://user-images.githubusercontent.com/34736972/34247507-9c8695ac-e62a-11e7-8164-fe6cd35d4e98.png)

Graphic packs enabled:
-FXAA
-High Res Shadows
-2K Res
-Contrasty
-FPS++
-30fps Lock
-LWZX Crash Workaround
-NVIDIA Explosions
-ReflExtra
-Square Kakariko Torch Fix

~Tried disabling each graphic pack and alternating between them, doesn't seem like 30FPS Lock is clashing with other packs since it causes that even when all packs are disabled, except itself.~
Explained in the latest comment.

Thanks!

**Comment by daninthemix** [comment] 2017-12-21 21:32
I don't have this issue. Of the ones you listed, the bold are the ones I have enabled:

-FXAA
**-High Res Shadows
-4K Res**
-Contrasty
-FPS++
**-30fps Lock
-LWZX Crash Workaround
-NVIDIA Explosions**
-ReflExtra
**-Square Kakariko Torch Fix**

**Comment by Quixoticed** [comment] 2017-12-22 04:17
What system config are you running on? Had a reply on Reddit saying it's an NVIDIA issue, I'm on a 1060 but not on the latest driver though it's the previous update.

Also, afaik 30FPS Lock **doesn't** work unless FPS++ is enabled and the game doesn't go above 30FPS by default _(at least, not for me even with fence skip)_.

**Comment by daninthemix** [comment] 2017-12-22 06:34
I'm on 388.13 (Nvidia driver), GTX1080, Windows 10 FCU. 30fps lock definitely does work without FPS++ - the reason I enabled it was to stop the 60fps / speedy Link in shrines bug caused by fence skip (which it did).

**Comment by Forkinator** [comment] 2017-12-27 01:12
having this same issue but not using the 30fps pack.

-FXAA
-High Res Shadows
-4K Res
-Clarity
-FPS++
-LWZX Crash Workaround
-NVIDIA Explosions
-ReflExtra
-Square Kakariko Torch Fix

**Comment by Quixoticed** [comment] 2017-12-29 06:28
Reinstalled CEMU and redumped BOTW files, can confirm FPS++ is causing the flickering instead of the 30FPS Lock. 
Seems like the flickering occurs more frequently the longer you have the game up.

**Comment by slashiee** [comment] 2017-12-29 06:51
probably will be fixed in the same update with fixed stamina and arrows

**Comment by e2zippo** [comment] 2018-01-13 13:28
I still have this issue. Using latest packs. Guessing it's not fixed?

**Comment by Crementif** [comment] 2018-01-26 15:25
Yup, it's not fixed yet.

**Comment by slashiee** [comment] 2018-02-02 20:52
Do the changes made for it for 1.11.4 help at all or no?

**Comment by Crementif** [comment] 2018-02-13 12:04
It didn't fix it, from what I've tested.

**Comment by xqdoo00o** [comment] 2018-04-30 05:41
not fixed yet.

**Comment by Rendarius** [comment] 2018-05-22 23:46
I had major flickering related to a different issue altogether, but this might be related and of significance....
Have you tried switching the GPU Buffer Accuracy Settings ?? 
If you are Set at High or Medium, try switching to Low....
Hope this helps and is something you might have over-looked trying.....

**Comment by Quixoticed** [comment] 2018-05-23 01:15
I'm not sure if the flickering you're experiencing is similar to what I get. But yes, GPU Buffer Accuracy is on Low, barely see any difference when set to the higher settings on BoTW. 

Flickering/flashing of that circle in the middle of the map still occurs with FPS++ on but the default Fenceskip disabled.

**Comment by Crementif** [comment] 2018-05-28 11:30
I think it's safe to say that this issue is pretty much never going to be fixed due to lost interest by it's sole author Xalphenos. It's a hack after-all. It might be revisited once Cemu will have it's own patches variant (probably only on the roadmap for now though, expect something along the lines of 1 year).

**Closed by Crementif** 2018-05-28 11:30 UTC

**Comment by Xalphenos** [comment] 2018-05-28 20:18
It also certainly doesn't help that it doesn't occur on my end.
