### ISSUE TITLE
[Xenoblade Chronicles X] Offline Tasks and mission

### ISSUE THREAD

**Issue by JobLeite** [slashiee/cemu_graphic_packs#381] opened 2019-06-20 17:29 UTC
Dear, good tare!

Someone could help me, as soon as I accept a Squad Mission when entering the mission closes the emulator.
[log.txt](https://github.com/slashiee/cemu_graphic_packs/files/3311483/log.txt)

**Comment by wakka1** [comment] 2019-06-25 08:22
The offline tasks and squad missions mod is buggy. If i finish a squad mission while the mod is active, the game will crash 100% on loading screen leading to mission results. The game works fine if i disable the mod while doing the mission and enabling it after going back to barracks.

**Comment by lasyan3** [comment] 2019-06-25 16:30
@wakka1 are you using 1.0.1E or 1.0.2U?

**Comment by lasyan3** [comment] 2019-06-25 18:04
Ok Just commited a new version of the mod, without the "tickets multiplicator" presets, as I suspect this is the root cause. So far I had no crash with this version. Please let me know :-).

**Comment by wakka1** [comment] 2019-06-26 14:15
@lasyan3 . Using 1.0.2U , tested twice with the new commit, it worked fine!
Btw, i'm taking this chance to mention another issue, both the BP and class exp multiplier mods crash at the network terminal when viewing missions/dlc , other multiplier mods probably the same but i haven't tested them.
 Thanks for your help!

**Comment by lasyan3** [comment] 2019-06-26 16:54
@wakka1 ok I think this must be the same kind of issue as for the Offline BLADE Missions mod. I'll check and keep you in touch.

**Comment by lasyan3** [comment] 2019-06-30 08:27
Just commited fixes for issues I found with Blade Offline and experience multiplier mods.
@wakka1 (and others too) please feel free to check it out and let me know if you're still having some issues.

**Comment by wakka1** [comment] 2019-06-30 13:17
@lasyan3, I tested the squad missions and exp/bp/class exp mods, no crashes at all now.
The multipliers works too.
Thanks.

**Comment by lasyan3** [comment] 2019-06-30 17:05
Glad to read that! @JobLeite Can you confirm it's ok for you too?

**Comment by JobLeite** [comment] 2019-06-30 17:53
@lasyan3 @wakka1 , tested, it works perfectly, thank you very much to everyone.

I was playing until now .... ^^

**Comment by lasyan3** [comment] 2019-06-30 19:44
Great, so we can close the issue :-)

**Closed by lasyan3** 2019-06-30 19:44 UTC
